# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-2.16.840.1.113883.3.1937.98.5.8.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-AIR.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-atc.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-CAPeCP.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-CDCNHSN.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-CDCREC-1.2.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-CDCREC-1.3.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-cvx.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-edqm.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-hcpcs.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-hl7-format-codes.json
# java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-HSLOC.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icd-9-cm.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icd-10-cm.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icd-10.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icd-o-3.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icd10PCS.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icf-2001a.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-icf-2017a.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-ICH-context-of-use.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-isco.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-iso3166-2.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-iso3166.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-loinc-supplement-uz.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-MDC-concept-status.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-MDC.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-mvx.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-nciThesaurus-fragment.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-nucc-provider-taxonomy.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-radlex.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-sevco.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-spdx.json
java -jar validator_cli.jar -version 4.0 -ig packages/fhir.tx.support.r4/package/CodeSystem-designation-usage.json -ig packages/fhir.tx.support.r4/package/CodeSystem-MDC-designation-use.json  -ig /Users/grahame/igs/extensions/input/definitions/CodeSystem -advisor-file advisor.txt packages/fhir.tx.support.r4/package/CodeSystem-usps.json