name: "Validate StructureMaps"

on:
  push:
  #  branches: master
  workflow_dispatch:

jobs:
  validate:
    name: "Validate StructureMaps"
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run transforms
      run: cd ./interversion/ && ./ci-run-validation.sh

    - name: Show environment variables
      run: echo "true"

  upload-results:
    name: "Upload results"
    runs-on: ubuntu-latest
    needs: validate

    strategy:
      matrix:
        names: [Account4to5, ActivityDefinition4to5, ActorDefinition4to5,
          Address4to5, AdministrableProductDefinition4to5, AdverseEvent4to5,
          Age4to5, AllergyIntolerance4to5, Annotation4to5, Appointment4to5,
          AppointmentResponse4to5, ArtifactAssessment4to5, Attachment4to5,
          AuditEvent4to5, Availability4to5, BackboneElement4to5, Basic4to5,
          Binary4to5, BiologicallyDerivedProduct4to5,
          BiologicallyDerivedProductDispense4to5, BodyStructure4to5, Bundle4to5,
          CanonicalResource4to5, CapabilityStatement4to5, CarePlan4to5,
          CareTeam4to5, ChargeItem4to5, ChargeItemDefinition4to5, Citation4to5,
          Claim4to5, ClaimResponse4to5, ClinicalImpression4to5,
          ClinicalUseDefinition4to5, CodeableConcept4to5, CodeSystem4to5,
          Coding4to5, Communication4to5, CommunicationRequest4to5,
          CompartmentDefinition4to5, Composition4to5, ConceptMap4to5,
          Condition4to5, ConditionDefinition4to5, Consent4to5, ContactDetail4to5,
          ContactPoint4to5, Contract4to5, Contributor4to5, Count4to5, Coverage4to5,
          CoverageEligibilityRequest4to5, CoverageEligibilityResponse4to5,
          DataRequirement4to5, DetectedIssue4to5, Device4to5,
          DeviceAssociation4to5, DeviceDefinition4to5, DeviceDispense4to5,
          DeviceMetric4to5, DeviceRequest4to5, DeviceUsage4to5,
          DiagnosticReport4to5, Distance4to5, DocumentReference4to5,
          DomainResource4to5, Dosage4to5, Duration4to5, Element4to5,
          ElementDefinition4to5, Encounter4to5, EncounterHistory4to5, Endpoint4to5,
          EnrollmentRequest4to5, EnrollmentResponse4to5, EpisodeOfCare4to5,
          EventDefinition4to5, Evidence4to5, EvidenceReport4to5,
          EvidenceVariable4to5, ExampleScenario4to5, ExplanationOfBenefit4to5,
          Expression4to5, ExtendedContactDetail4to5, Extension4to5,
          FamilyMemberHistory4to5, Flag4to5, FormularyItem4to5, GenomicStudy4to5,
          Goal4to5, GraphDefinition4to5, Group4to5, GuidanceResponse4to5,
          HealthcareService4to5, HumanName4to5, Identifier4to5,
          ImagingSelection4to5, ImagingStudy4to5, Immunization4to5,
          ImmunizationEvaluation4to5, ImmunizationRecommendation4to5,
          ImplementationGuide4to5, Ingredient4to5, InsurancePlan4to5,
          InventoryItem4to5, InventoryReport4to5, Invoice4to5, Library4to5,
          Linkage4to5, List4to5, Location4to5, ManufacturedItemDefinition4to5,
          MarketingStatus4to5, Measure4to5, MeasureReport4to5, Medication4to5,
          MedicationAdministration4to5, MedicationDispense4to5,
          MedicationKnowledge4to5, MedicationRequest4to5, MedicationStatement4to5,
          MedicinalProductDefinition4to5, MessageDefinition4to5, MessageHeader4to5,
          Meta4to5, MetadataResource4to5, MolecularSequence4to5,
          MonetaryComponent4to5, Money4to5, NamingSystem4to5, Narrative4to5,
          NutritionIntake4to5, NutritionOrder4to5, NutritionProduct4to5,
          Observation4to5, ObservationDefinition4to5, OperationDefinition4to5,
          OperationOutcome4to5, Organization4to5, OrganizationAffiliation4to5,
          PackagedProductDefinition4to5, ParameterDefinition4to5, Parameters4to5,
          Patient4to5, PaymentNotice4to5, PaymentReconciliation4to5, Period4to5,
          Permission4to5, Person4to5, PlanDefinition4to5, Population4to5,
          Practitioner4to5, PractitionerRole4to5, primitives4to5,
          PrimitiveType4to5, Procedure4to5, ProductShelfLife4to5, Provenance4to5,
          Quantity4to5, Questionnaire4to5, QuestionnaireResponse4to5, Range4to5,
          Ratio4to5, Reference4to5, RegulatedAuthorization4to5,
          RelatedArtifact4to5, RelatedPerson4to5, RequestOrchestration4to5,
          Requirements4to5, ResearchStudy4to5, ResearchSubject4to5, Resource4to5,
          RiskAssessment4to5, SampledData4to5, Schedule4to5, SearchParameter4to5,
          ServiceRequest4to5, Signature4to5, Slot4to5, Specimen4to5,
          SpecimenDefinition4to5, StructureDefinition4to5, StructureMap4to5,
          Subscription4to5, SubscriptionStatus4to5, SubscriptionTopic4to5,
          Substance4to5, SubstanceDefinition4to5, SubstanceNucleicAcid4to5,
          SubstancePolymer4to5, SubstanceProtein4to5,
          SubstanceReferenceInformation4to5, SubstanceSourceMaterial4to5,
          SupplyDelivery4to5, SupplyRequest4to5, Task4to5,
          TerminologyCapabilities4to5, TestPlan4to5, TestReport4to5,
          TestScript4to5, Timing4to5, Transport4to5, TriggerDefinition4to5,
          UsageContext4to5, ValueSet4to5, VerificationResult4to5,
          VirtualServiceDetail4to5, VisionPrescription4to5]

    steps:
      - run: echo "The value of ${{ matrix.env_var }} is ${{ env[matrix.env_var] }}"

    # - name: Upload results
    #   uses: vadi2/gsheets-append-action@development
    #   with:
    #     GOOGLE_USER_MAIL: ${{secrets.GOOGLE_SPREADSHEET_EMAIL}}
    #     GOOGLE_USER_KEY: ${{secrets.GOOGLE_SPREADSHEET_KEY}}
    #     SPREADSHEET: '1bIg0eQQgHArr7eWyVP4Vhedo4qkfjyKzqRPO4PxxuNg'
    #     UPDATE: 'true'
    #     TABLE_START_CELL: 'D2'
    #     DATA_ENV_NAME: 'VALIDATION_OUTPUT'
    #   env:
    #     VALIDATION_OUTPUT: "one\ntwo\nthree"